# Generated by Django 3.2.16 on 2022-11-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YelpUser',
            fields=[
                ('user_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('yelping_since', models.DateTimeField()),
                ('useful', models.PositiveIntegerField(default=0)),
                ('funny', models.PositiveIntegerField(default=0)),
                ('cool', models.PositiveIntegerField(default=0)),
                ('fans', models.PositiveIntegerField(default=0)),
                ('friends', models.TextField(blank=True, null=True)),
                ('elite', models.TextField(blank=True, null=True)),
                ('average_stars', models.FloatField()),
                ('compliment_hot', models.PositiveIntegerField(default=0)),
                ('compliment_more', models.PositiveIntegerField(default=0)),
                ('compliment_profile', models.PositiveIntegerField(default=0)),
                ('compliment_cute', models.PositiveIntegerField(default=0)),
                ('compliment_list', models.PositiveIntegerField(default=0)),
                ('compliment_note', models.PositiveIntegerField(default=0)),
                ('compliment_plain', models.PositiveIntegerField(default=0)),
                ('compliment_cool', models.PositiveIntegerField(default=0)),
                ('compliment_funny', models.PositiveIntegerField(default=0)),
                ('compliment_writer', models.PositiveIntegerField(default=0)),
                ('compliment_photos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
