# Generated by Django 3.2.16 on 2022-11-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('stars', models.FloatField(default=0)),
                ('useful', models.PositiveIntegerField(default=0)),
                ('funny', models.PositiveIntegerField(default=0)),
                ('cool', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('business_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.yelpuser')),
            ],
        ),
    ]
